baseURL = "http://example.org/"
languageCode = "en-gb"
title = "My New Hugo Site"
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
  [markup.pandoc]
    citeproc = true
