baseURL = "http://algopattern.github.io/"
languageCode = "en-gb"
title = "Alpaca"
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
  [markup.pandoc]
    citeproc = true
